### ISSUE TITLE
Поправить ссылку в Литературе для начинающих, Н. Вирт. Алгоритмы + структуры данных = программы (1977)

### ISSUE THREAD

**Issue by amordo** [true-grue/Compiler-Development#2]
Не удается получить файл [по указанной ссылке](http://snilit.tspu.ru/uploads/files/default/virt.pdf).
Нашел [этот же экземпляр](https://b-ok.cc/book/2399429/ccc7cb) (оригинальное издание - 1976, перевод - 1985, раздел про трансляторы - имеется).
<img src="https://user-images.githubusercontent.com/23224148/88467700-68899800-cee2-11ea-84af-2122dbdb505f.png" width="300">

**Comment by true-grue** [comment]
Спасибо, изменил ссылку на Вашу.
